### ISSUE TITLE
Tau Weapons Do Less Damage Than Lasguns

### ISSUE THREAD

**Issue by OmenVI** [Daelso/Cadia-Station-40k#34]
The pulse carbine does less damage than a lasgun
The pulse pistol does the same damage as a pulse cargbine
The burst cannon does the same amount of damage as a pulse carbine per shot, but it also stops the burst when you move
The only weapon that does good damage is the pulse blaster, and there's only 2 of them

BUFF TAU

**Comment by Doosteroni** [comment]
No.

**Comment by RAND0MPR0** [comment]
Carbine does 10 damage (BEFORE armour, the autocannon also does 10 damage, and it fires ELEVEN times and is considered a bad weapon)
Rifle does 50 damage, they have same fire-rate and bullet spread...
There are about 10 of each but the rifles are hidden in one spot so most people miss them.
The Tau blaster does 75 damage per pellet, and shoots two (rather bad bullet spread but will insta-crit guardsmen at pointblank), but there are only two on the ship. Just make carbines do like 40 damage or something.

**Comment by Sancronis** [comment]
There's a pull request about this rn https://github.com/Daelso/Cadia-Station-40k/pull/35
Carbine is intended to do 30.

**Comment by Daelso** [comment]
fixed
